backend:
  name: git-gateway
  branch: main
media_folder: "src/assets/img"
public_folder: "/assets/img"
collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "base.njk"}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Permalink", name: "permalink", widget: "string", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
