backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/img"
public_folder: "/assets/img"

collections:
  - name: "news"
    label: "News"
    folder: "src/collections/news"
    create: true
    slug: "news-{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "datetime", required: true}
      - {label: "Content", name: "content", widget: "markdown"}

  - name: "works"
    label: "Works"
    folder: "src/collections/works"
    create: true
    slug: "works-{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Image name", name: "image", widget: "string"}
      - {label: "Content", name: "content", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    slug: "page-{{title}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "base.njk"}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Permalink", name: "permalink", widget: "string", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
